### ISSUE TITLE
[1.19.2] Cant start the game

### ISSUE THREAD

**Issue by pewblaze** [WebCoder49/dolphinsofthedeep#46]
Hi i cant start the game. I guess its a mod incomp. ^^" But idk what causes it exactly
My log:
https://gist.github.com/pewblaze/1e256b14655bdea604c5001013ab4494

**Comment by WebCoder49** [comment]
Thank you for pointing this bug out, @pewblaze . 

Sorry for taking a while to respond due to other commitments; I will try to fix this bug and send you a prerelease ASAP to test.

**Comment by WebCoder49** [comment]
I think it's because Minecraft 1.19.2 has a slightly different music disc constructor. I will **update the mod to use the latest MC version and send it to you ASAP.**

1.19: The mod's testing environment
![1.19 Constructor](https://user-images.githubusercontent.com/69071853/188503710-2a390af0-4737-4a28-a886-a16e05ea6bd5.png)

1.19.2: Your environment
![1.19.2 Constructor](https://user-images.githubusercontent.com/69071853/188503740-f503a02f-26b4-4dd5-ab9a-247202584846.png)

**Comment by WebCoder49** [comment]
Does this work, and if you have time, does it support the Dolphin Dance music disc? I haven't had time to test it properly.

https://github.com/WebCoder49/dolphinsofthedeep/releases/tag/v.1.0.1-alpha

**Comment by pewblaze** [comment]
No problem! I can wait :) 
I tested it & sadly i cant start the game :( But its another error now? ^^" 
https://gist.github.com/pewblaze/9b4415b36e419904326ade68718493af

**Comment by WebCoder49** [comment]
Sorry for the error. I will get back to you when I have time to update and test it.

**Comment by WebCoder49** [comment]
The bug appears to be this:
1. A river biome is loaded, including the pink river dolphin generation (l706)
2. A raid is loaded, and vanilla code tries to load the `minecraft:rhombus` banner pattern (l698)
3. It can't find the pattern in the registry, and throws an error (l694)

The game works fine for me; I think one of the other mods you are using might have caused this, as I haven't used banner patterns. Maybe you could try removing DolphinsOfTheDeep to confirm if the bug is externally caused?

I am sorry that I couldn't fix this, and hope that you manage to play with the mods soon.

**Comment by pewblaze** [comment]
So i tested again and its a nono again buuut i also did a Pack with only this mod and Terralith (cause of the river thing) and it didnt work. I deleted Terralith and it also didnt work? No im confused again cause it should work without any mods? 
https://gist.github.com/pewblaze/6884b657aab8448c5af42440eda2c313

But i guess its another error again? ^^"

**Comment by WebCoder49** [comment]
The error message and bug suggest that you're still using v1.0.0. That's not been updated from 1.19 to 1.19.2. Downloading [1.0.1-beta.1](https://github.com/WebCoder49/dolphinsofthedeep/releases/tag/v.1.0.1-alpha)'s jar file should work; that's what I was using for testing.

**Comment by WebCoder49** [comment]
[Here's a direct link to the file I was talking about.](https://github.com/WebCoder49/dolphinsofthedeep/releases/download/v.1.0.1-alpha/dolphinsofthedeep-1.0.1-beta.1.jar)

**Comment by WebCoder49** [comment]
I hope that this is useful; please let me know if the new version fixes it, or if there are still bugs.

**Comment by pewblaze** [comment]
Sorry but didnt work either ^^"
https://gist.github.com/pewblaze/efd6b82e1094e220e56536218006b100

Maybe i can find the mod sometimes :) But i guess it shouldnt be. But thank you for the hard work! Ive got so many mods & i really cant tell which one it could be :/
